version: '3.6'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - client
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always

  client:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
